import React from 'react';
import {
  HelpCircle,
  Activity,
  TrendingDown,
  Volume2,
  Gauge,
  Zap,
  CheckCircle2,
  AlertTriangle,
  Layers,
  Sparkles,
} from 'lucide-react';
import Card from './Card';
import Badge from './Badge';
import StatusBadge from './StatusBadge';

export const ExplainabilityPanel = ({
  recommendation,
  emotion,
  lapStats,
  correlation,
  transcript,
  className = '',
}) => {
  const stressScore = emotion?.stressScore || 78;
  const driverState = emotion?.driverState || 'Stressed';
  const confidence = emotion?.confidence || 94.2;
  const paceLoss = correlation?.paceLossSeconds || '0.84';
  const riskScore = correlation?.riskScore || 61;
  const riskTier = correlation?.riskTier || 'High';

  const weights = [
    {
      label: 'Driver Emotion & Acoustic Stress',
      weight: 40,
      value: `${stressScore}% Stress (${driverState})`,
      severity: stressScore >= 65 ? 'critical' : 'nominal',
      color: 'bg-rose-500',
    },
    {
      label: 'Lap Pace Degradation Trend',
      weight: 30,
      value: `+${paceLoss}s / lap (Worsening)`,
      severity: 'critical',
      color: 'bg-rose-500',
    },
    {
      label: 'Consecutive Radio Stress Events',
      weight: 20,
      value: '2 Spikes in Stint (Laps 16 & 18)',
      severity: 'critical',
      color: 'bg-amber-400',
    },
    {
      label: 'Session Strategy & Undercut Window',
      weight: 10,
      value: 'Lap 21 Pit Entry Target',
      severity: 'nominal',
      color: 'bg-zinc-900 dark:bg-white',
    },
  ];

  const evidenceItems = [
    {
      title: 'Vocal Stress & Prosody Detected',
      detail: `Pitch jitter shifted +42.5 Hz with speech cadence at 185 WPM (${confidence}% model confidence).`,
      status: 'critical',
      icon: Activity,
    },
    {
      title: 'Sector 2 Apex Exit Degradation',
      detail: `Lap time slowed to 1:31.240 (+1.82s vs stint best), with Sector 2 degraded by +0.51s due to Turn 4 understeer.`,
      status: 'critical',
      icon: TrendingDown,
    },
    {
      title: 'Consecutive Stressed Transmission History',
      detail: `Driver reported traffic on Lap 16 followed by severe front-left slip on Lap 18.`,
      status: 'nominal',
      icon: Volume2,
    },
    {
      title: 'Composite Risk Escalation Threshold',
      detail: `Performance Risk Score reached ${riskScore}% (${riskTier} Tier), triggering automated pit directive.`,
      status: 'critical',
      icon: Gauge,
    },
  ];

  return (
    <Card
      title="AI Decision Explainability & Root Cause Attribution"
      subtitle="Why this tactical recommendation was generated by the multi-factor intelligence engine"
      action={<Badge variant="white" size="sm">Explainable AI</Badge>}
      className={className}
    >
      <div className="space-y-6">
        
        {/* Recommendation Directive Banner */}
        <div className="p-4 rounded-lg bg-zinc-950 text-white dark:bg-zinc-100 dark:text-zinc-950 space-y-2 shadow-2xs">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Zap className="w-4 h-4 text-rose-400 dark:text-rose-600 flex-shrink-0" />
              <span className="font-semibold text-xs">
                ACTIONABLE DIRECTIVE: {recommendation?.category || 'Radio Brevity & Pit Protocol'}
              </span>
            </div>
            <StatusBadge status="critical" size="sm">
              Risk Score {riskScore}%
            </StatusBadge>
          </div>
          <p className="text-xs leading-relaxed opacity-95 pl-6 font-normal">
            "{recommendation?.action || 'Enforce radio silence through Sector 2 high-G corners and prepare Lap 21 pit window for Hard compound.'}"
          </p>
        </div>

        {/* 2-Column: Multi-Factor Weighted Breakdown + Evidence List */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-xs">
          
          {/* Left: Weighted Decision Breakdown with Animated Progress Bars */}
          <div className="space-y-3 p-4 rounded-lg bg-zinc-50/70 dark:bg-zinc-900/40 border border-zinc-200/60 dark:border-zinc-800/60">
            <div className="flex items-center justify-between pb-2 border-b border-zinc-200/60 dark:border-zinc-800">
              <span className="font-semibold text-zinc-950 dark:text-white flex items-center gap-1.5">
                <Layers className="w-3.5 h-3.5 text-zinc-500" />
                Decision Weight Attribution
              </span>
              <span className="text-[11px] text-zinc-400">Total: 100%</span>
            </div>

            <div className="space-y-3 pt-1">
              {weights.map((w, idx) => (
                <div key={idx} className="space-y-1">
                  <div className="flex justify-between text-[11px]">
                    <span className="text-zinc-600 dark:text-zinc-400 font-medium">
                      {w.label} <strong className="text-zinc-900 dark:text-zinc-200">({w.weight}%)</strong>
                    </span>
                    <span className="font-medium text-zinc-950 dark:text-white font-tabular">
                      {w.value}
                    </span>
                  </div>
                  <div className="w-full bg-zinc-200 dark:bg-zinc-800 h-1.5 rounded-full overflow-hidden">
                    <div
                      className={`h-full rounded-full ${w.color} transition-all duration-700`}
                      style={{ width: `${w.weight * 2.5}%` }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Right: Itemized Telemetry Evidence List */}
          <div className="space-y-3 p-4 rounded-lg bg-zinc-50/70 dark:bg-zinc-900/40 border border-zinc-200/60 dark:border-zinc-800/60">
            <div className="flex items-center justify-between pb-2 border-b border-zinc-200/60 dark:border-zinc-800">
              <span className="font-semibold text-zinc-950 dark:text-white flex items-center gap-1.5">
                <Sparkles className="w-3.5 h-3.5 text-rose-500" />
                Root-Cause Telemetry Evidence
              </span>
              <Badge variant="outline" size="sm">4 Factors</Badge>
            </div>

            <div className="space-y-2.5 pt-1">
              {evidenceItems.map((item, idx) => {
                const Icon = item.icon;
                return (
                  <div key={idx} className="flex items-start gap-2.5 text-[11px] leading-relaxed">
                    <div className="w-4 h-4 rounded-full bg-zinc-200/60 dark:bg-zinc-800 flex items-center justify-center flex-shrink-0 mt-0.5">
                      <Icon className="w-2.5 h-2.5 text-zinc-600 dark:text-zinc-300" />
                    </div>
                    <div className="space-y-0.5 flex-1">
                      <span className="font-semibold text-zinc-950 dark:text-white block">
                        {item.title}
                      </span>
                      <p className="text-zinc-500 dark:text-zinc-400">
                        {item.detail}
                      </p>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

        </div>

      </div>
    </Card>
  );
};

export default ExplainabilityPanel;
