import React from 'react';
import {
  HelpCircle,
  Activity,
  TrendingDown,
  Volume2,
  Gauge,
  Zap,
  CheckCircle2,
  AlertTriangle,
  Layers,
  Sparkles,
} from 'lucide-react';
import Card from './Card';
import Badge from './Badge';
import StatusBadge from './StatusBadge';

export const ExplainabilityPanel = ({
  recommendation,
  emotion,
  lapStats,
  correlation,
  transcript,
  className = '',
}) => {
  const stressScore = emotion?.stressScore || correlation?.stressScore || 78;
  const driverState = emotion?.driverState || correlation?.driverState || 'Stressed';
  const confidence = correlation?.confidence || emotion?.confidence || 94.2;
  const degradationStr = correlation?.performanceDegradationStr || '+1.43 s/lap';
  const paceLossStr = correlation?.paceLossPercentageStr || '+1.59%';
  const riskScore = correlation?.riskScore || 61;
  const riskTier = correlation?.riskTier || 'High';
  const stressLap = correlation?.stressLap || 18;

  const activeAction =
    recommendation?.action ||
    correlation?.recommendation?.action ||
    'Driver stress is affecting pace. Consider reducing radio traffic and evaluating tire condition.';

  const activeCategory =
    recommendation?.category ||
    correlation?.recommendation?.category ||
    'Radio Brevity & Pit Protocol';

  const weights = [
    {
      label: 'Driver Emotion & Acoustic Stress',
      weight: 40,
      value: `${stressScore}% Stress (${driverState})`,
      severity: stressScore >= 65 ? 'critical' : 'nominal',
      color: 'bg-rose-500',
    },
    {
      label: 'Lap Pace Degradation Trend',
      weight: 30,
      value: `${degradationStr} (${paceLossStr})`,
      severity: 'critical',
      color: 'bg-rose-500',
    },
    {
      label: 'Consecutive Radio Stress Events',
      weight: 20,
      value: `Spike at Lap ${stressLap}`,
      severity: 'critical',
      color: 'bg-amber-500',
    },
    {
      label: 'Session Strategy & Undercut Window',
      weight: 10,
      value: 'Lap 21 Pit Entry Target',
      severity: 'nominal',
      color: 'bg-zinc-900 dark:bg-white',
    },
  ];

  const evidenceItems = [
    {
      title: 'Vocal Stress & Prosody Detected',
      detail: `Pitch jitter shifted ${emotion?.pitchJitter || '+42.5 Hz'} with speech cadence at ${emotion?.speechCadence || '185 WPM'} (${confidence}% STT/emotion model confidence).`,
      status: 'critical',
      icon: Activity,
    },
    {
      title: 'Sector 2 Apex Exit Degradation',
      detail: `Lap pace slowed to ${correlation?.avgAfterStressTime || '1:31.240'} (${degradationStr} delta), with post-stress tire temperature spike on Lap ${stressLap}.`,
      status: 'critical',
      icon: TrendingDown,
    },
    {
      title: 'Consecutive Stressed Transmission History',
      detail: `Driver reported "${transcript || 'The rear tires are overheating.'}" at Lap ${stressLap}, confirming aerodynamic grip loss.`,
      status: 'nominal',
      icon: Volume2,
    },
    {
      title: 'Composite Risk Escalation Threshold',
      detail: `Performance Risk Score reached ${riskScore}% (${riskTier} Tier), triggering automated pit wall strategy directive.`,
      status: 'critical',
      icon: Gauge,
    },
  ];

  return (
    <Card
      title="AI Decision Explainability & Root Cause Attribution"
      subtitle="Why this tactical recommendation was generated by the multi-factor intelligence engine"
      action={<Badge variant="white" size="sm">Explainable AI</Badge>}
      className={className}
    >
      <div className="space-y-5">
        
        {/* Recommendation Directive Banner */}
        <div className="p-4 rounded-xl bg-zinc-950 text-white dark:bg-zinc-100 dark:text-zinc-950 space-y-2 shadow-sm">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <div className="flex items-center gap-2">
              <Zap className="w-4 h-4 text-rose-400 dark:text-rose-600 flex-shrink-0" />
              <span className="font-bold text-xs uppercase tracking-wide">
                ACTIONABLE DIRECTIVE: {activeCategory}
              </span>
            </div>
            <StatusBadge status="critical" size="sm">
              Risk Score {riskScore}%
            </StatusBadge>
          </div>
          <p className="text-xs sm:text-sm leading-relaxed opacity-95 pl-6 font-normal italic">
            "{activeAction}"
          </p>
        </div>

        {/* 2-Column: Multi-Factor Weighted Breakdown + Evidence List */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 sm:gap-6 text-xs">
          
          {/* Left: Weighted Decision Breakdown with Animated Progress Bars */}
          <div className="space-y-3 p-4 rounded-xl bg-zinc-50/80 dark:bg-zinc-900/50 border border-zinc-200/60 dark:border-zinc-800/60 flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between pb-2.5 border-b border-zinc-200/60 dark:border-zinc-800">
                <span className="font-bold text-zinc-950 dark:text-white flex items-center gap-1.5 text-xs">
                  <Layers className="w-3.5 h-3.5 text-zinc-500" />
                  Decision Weight Attribution
                </span>
                <span className="text-[11px] text-zinc-400 font-mono">Total: 100%</span>
              </div>

              <div className="space-y-3.5 pt-3">
                {weights.map((w, idx) => (
                  <div key={idx} className="space-y-1.5">
                    <div className="flex justify-between items-baseline text-[11px]">
                      <span className="text-zinc-600 dark:text-zinc-400 font-medium truncate max-w-[200px] sm:max-w-none">
                        {w.label} <strong className="text-zinc-900 dark:text-zinc-200 font-semibold">({w.weight}%)</strong>
                      </span>
                      <span className="font-bold text-zinc-950 dark:text-white font-mono text-[11px]">
                        {w.value}
                      </span>
                    </div>
                    <div className="w-full bg-zinc-200/70 dark:bg-zinc-800 h-1.5 rounded-full overflow-hidden">
                      <div
                        className={`h-full rounded-full ${w.color} transition-all duration-700`}
                        style={{ width: `${w.weight * 2.5}%` }}
                      />
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Right: Itemized Telemetry Evidence List */}
          <div className="space-y-3 p-4 rounded-xl bg-zinc-50/80 dark:bg-zinc-900/50 border border-zinc-200/60 dark:border-zinc-800/60 flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between pb-2.5 border-b border-zinc-200/60 dark:border-zinc-800">
                <span className="font-bold text-zinc-950 dark:text-white flex items-center gap-1.5 text-xs">
                  <Sparkles className="w-3.5 h-3.5 text-rose-500" />
                  Root-Cause Telemetry Evidence
                </span>
                <Badge variant="outline" size="sm">4 Factors</Badge>
              </div>

              <div className="space-y-2.5 pt-3">
                {evidenceItems.map((item, idx) => {
                  const Icon = item.icon;
                  return (
                    <div key={idx} className="flex items-start gap-2.5 text-[11px] leading-relaxed">
                      <div className="w-5 h-5 rounded-md bg-zinc-200/70 dark:bg-zinc-800 flex items-center justify-center flex-shrink-0 mt-0.5 shadow-2xs">
                        <Icon className="w-3 h-3 text-zinc-600 dark:text-zinc-300" />
                      </div>
                      <div className="space-y-0.5 flex-1 min-w-0">
                        <span className="font-bold text-zinc-950 dark:text-white block truncate">
                          {item.title}
                        </span>
                        <p className="text-zinc-500 dark:text-zinc-400 text-[11px]">
                          {item.detail}
                        </p>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>

        </div>

      </div>
    </Card>
  );
};

export default ExplainabilityPanel;
